### All this based on
# - https://medium.com/@tiangolo/angular-in-docker-with-nginx-supporting-environments-built-with-multi-stage-docker-builds-bb9f1724e984
# - https://mherman.org/blog/dockerizing-an-angular-app/
###
# Prod - docker build -t sparrow-sidecar:prod .
#        docker run -p 80:80 sparrow-sidecar:prod
# Dev  - docker build -t sparrow-sidecar:dev --build-arg configuration="" .
#        docker run -p 80:80 sparrow-sidecar:dev
###

# Stage 0, "build-stage", based on Node.js, to build and compile Angular
FROM tiangolo/node-frontend:latest as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration
# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:latest
COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
